
export class ServiceManager {

    // _SupercondActor context object must be injected at runtime
    constructor(private supercondActor: SupercondActor.ISupercondActor) { }

    // Application name must be in URI format and start with 'fabric:/'
    //appName: string = 'fabric:/SupercondActor.Service.Test';
    appName: string = 'fabric:/SupercondActor.Platform.BusinessServicesApp';

    async runTestCycle() {
        try {
            let runCounter = await this.updateRunCounter();
            let appExists = await this.checkIfApplicationExists(this.appName);

            if (appExists) {
                await this.createTestServices(runCounter);
            }
            else {
                await this.createTestApplication();
            }
        }
        catch (err) {
            this.supercondActor.Logger.logError('Error executing method runTestCycle: ' + err);
        }
    }

    async updateRunCounter(): Promise<number> {
        // get run counter
        let runCounter: number = await this.supercondActor.Service.getLocalStateAsync('runCounter');
        if (!++runCounter) {
            runCounter = 0;
        }
        this.supercondActor.Logger.logInfo(`Executing ServiceManager cycle #${runCounter}.`);
        // save run counter
        await this.supercondActor.Service.saveLocalStateAsync('runCounter', runCounter);
        return runCounter;
    }

    async checkIfApplicationExists(appName: string): Promise<boolean> {
        // trying to find the application
        let appList = await this.supercondActor.Service.getApplicationsAsync();
        let appInfo = appList.find(a => a.applicationName === appName);
        return !!appInfo;
    }

    async createTestApplication() {
        // create application
        this.supercondActor.Logger.logInfo(['Creating test application...', this.appName]);
        await this.supercondActor.Service.createApplicationAsync(this.appName);
        await this.supercondActor.Service.saveLocalStateAsync('appName', this.appName);
        this.supercondActor.Logger.logInfo(['Created test application', this.appName]);

        // create API service
        this.supercondActor.Logger.logInfo('Creating Test Api Service...');
        let apiServiceConfig = this.getApiServiceConfig();
        let apiServiceUri = await this.supercondActor.Service.createOrUpdateApiServiceAsync(apiServiceConfig, this.appName);

        this.supercondActor.Logger.logInfo(['Created Test Api Service', apiServiceUri]);
    }

    getApiServiceConfig(): SupercondActor.IApiServiceConfig {
        // provide API service configuration
        let serviceConfig: SupercondActor.IApiServiceConfig = {
            serviceName: 'Test Api Service',
            groupName: 'Generated Services',
            instanceCount: -1,
            metadataJson: '{ "description": "Generated by ServiceManager scheduled service" }',
            enableADAuthentication: false,
            configureProxy: true,
            serveFiles: false,
            proxyConfiguration: [
                {
                    "Key": "traefik.frontend.rule",
                    "Value": "PathPrefixStrip: /api/testapp"
                }
            ],
            serviceScript: `let TestServiceManager = new MyServiceTypes.ServiceManager(_SupercondActor_Context);
let counters = await TestServiceManager.reportServiceCounts();
_SupercondActor_Context.Logger.logInfo(['Awailable test services', counters]);
return counters;`,
            stopRequested: false
        };
        return serviceConfig;
    }

    async reportServiceCounts() {
        let longrunningPr = await this.supercondActor.Service.getLongRunningServicesAsync(this.appName);
        let scheduledPr = await this.supercondActor.Service.getScheduledServicesAsync(this.appName);

        const [longrunning, scheduled] = await Promise.all([longrunningPr, scheduledPr]);

        return {
            longrunningCount: longrunning.length,
            scheduledCount: scheduled.length
        };
    }

    async createTestServices(runCounter: number) {
        // create Scheduled service
        let serviceConfig = this.getScheduledServiceConfig(runCounter);
        try {
            this.supercondActor.Logger.logInfo('Before creating Scheduled Service');
            let serviceUri = await this.supercondActor.Service.createOrUpdateScheduledServiceAsync(serviceConfig, this.appName);
            this.supercondActor.Logger.logInfo([`Created Test Scheduled Service #${runCounter}`, serviceUri]);
        }
        catch (err) {
            this.supercondActor.Logger.logError('Error creating Scheduled Service: ' + err);
        }
        // create Long-running service
        let lrServiceConfig = this.getLongRunningServiceConfig(runCounter);
        this.supercondActor.Logger.logInfo('Before creating LongRunning Service');
        let lrServiceUri = await this.supercondActor.Service.createOrUpdateLongRunningServiceAsync(lrServiceConfig, this.appName);
        this.supercondActor.Logger.logInfo([`Created Test Long-running Service #${runCounter}`, lrServiceUri]);
    }

    getScheduledServiceConfig(runCounter: number): SupercondActor.IScheduledServiceConfig {
        let serviceConfig: SupercondActor.IScheduledServiceConfig = {
            serviceName: `Test Scheduled Service #${runCounter}`,
            groupName: 'Generated Services',
            metadataJson: '{ "description": "Generated by ServiceManager scheduled service" }',
            job: {
                jobSchedule: {
                    intervalSeconds: 15
                },
                stopRequested: false,
                jobScript: `let TestServiceManager = new MyServiceTypes.ServiceManager(_SupercondActor_Context);
let results = await TestServiceManager.runSystemTests();
_SupercondActor_Context.Logger.logInfo(['Scheduled Service #${runCounter} Test results', results]);
return results;`
            }
        };
        return serviceConfig;
    }

    getLongRunningServiceConfig(runCounter: number): SupercondActor.ILongRunningServiceConfig {
        let serviceConfig: SupercondActor.ILongRunningServiceConfig = {
            serviceName: `Test Long-running Service #${runCounter}`,
            instanceCount: -1,
            groupName: 'Generated Services',
            metadataJson: '{ "description": "Generated by ServiceManager scheduled service" }',
            stopRequested: true,
            serviceScript: `let TestServiceManager = new MyServiceTypes.ServiceManager(_SupercondActor_Context);
while (true) {
    _SupercondActor_Context.Logger.logInfo('Long-running Service #${runCounter} health check');
    let results = await TestServiceManager.runSystemTests();
    _SupercondActor_Context.Logger.logInfo(['Long-running Service #${runCounter} Test results', results]);
    await TestServiceManager.sleep(17000);
}`
        };
        return serviceConfig;
    }

    async runSystemTests() {
        this.supercondActor.Logger.logInfo(['Testing...', 1]);
        let counters = await this.reportServiceCounts();
        this.supercondActor.Logger.logInfo(['Service counters', counters]);
        return counters;
    }

    sleep(ms: number) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}