import axios, { AxiosPromise } from 'axios';
const https = require('https');

export class TestManager {

    // _SupercondActor context object must be injected at runtime
    constructor(private supercondActor: SupercondActor.ISupercondActor) { }

    // Application name must be in URI format and start with 'fabric:/'
    appName: string = 'fabric:/SupercondActor.TestApp';
    //appName: string = 'fabric:/SupercondActor.Platform.BusinessServicesApp';

    async runTestCycle() {
        try {
            let appExists = await this.checkIfApplicationExists(this.appName);

            if (appExists) {
                let runCounter = await this.updateRunCounter();
                await this.createTestServices(runCounter);
            }
            else {
                await this.createTestApplication();
            }
        }
        catch (err) {
            this.supercondActor.Logger.logError('Error executing method runTestCycle: ' + err);
        }
    }

    async updateRunCounter(): Promise<number> {
        // get run counter
        let runCounter: number = await this.supercondActor.Service.getLocalStateAsync('runCounter');
        if (!++runCounter) {
            runCounter = 0;
        }
        this.supercondActor.Logger.logInfo(`Executing TestManager cycle #${runCounter}.`);
        // save run counter
        await this.supercondActor.Service.saveLocalStateAsync('runCounter', runCounter);
        return runCounter;
    }

    async checkIfApplicationExists(appName: string): Promise<boolean> {
        // trying to find the application
        let appList = await this.supercondActor.Service.getApplicationsAsync();
        let appInfo = appList.find(a => a.applicationName === appName);
        return !!appInfo;
    }

    async createTestApplication() {
        // create application
        this.supercondActor.Logger.logInfo(['Creating test application...', this.appName]);
        await this.supercondActor.Service.createApplicationAsync(this.appName);
        await this.supercondActor.Service.saveLocalStateAsync('appName', this.appName);
        this.supercondActor.Logger.logInfo(['Created test application', this.appName]);

        // create API service
        this.supercondActor.Logger.logInfo('Creating root Api Service...');
        let apiServiceConfig = this.getRootApiServiceConfig();
        let apiServiceUri = await this.supercondActor.Service.createOrUpdateApiServiceAsync(apiServiceConfig, this.appName);
        this.supercondActor.Logger.logInfo(['Created root Api Service', apiServiceUri]);
    }

    async createTestServices(runCounter: number) {
        // create API service
        let apiServiceConfig = this.getTestApiServiceConfig(runCounter);
        let apiServiceUri = await this.supercondActor.Service.createOrUpdateApiServiceAsync(apiServiceConfig, this.appName);
        this.supercondActor.Logger.logInfo([`Created Test API Service #${runCounter}`, apiServiceUri]);

        // create Scheduled service
        let schServiceConfig = this.getTestScheduledServiceConfig(runCounter);
        let schServiceUri = await this.supercondActor.Service.createOrUpdateScheduledServiceAsync(schServiceConfig, this.appName);
        this.supercondActor.Logger.logInfo([`Created Test Scheduled Service #${runCounter}`, schServiceUri]);

        // create Long-running service
        let lrServiceConfig = this.getTestLongRunningServiceConfig(runCounter);
        let lrServiceUri = await this.supercondActor.Service.createOrUpdateLongRunningServiceAsync(lrServiceConfig, this.appName);
        this.supercondActor.Logger.logInfo([`Created Test Long-running Service #${runCounter}`, lrServiceUri]);
    }

    getRootApiServiceConfig(): SupercondActor.IApiServiceConfig {
        // provide API service configuration
        let serviceConfig: SupercondActor.IApiServiceConfig = {
            serviceName: `Root API Service`,
            groupName: 'Generated Services',
            instanceCount: -1,
            metadataJson: '{ "description": "Generated by TestManager scheduled service" }',
            enableADAuthentication: false,
            configureProxy: true,
            serveFiles: false,
            proxyConfiguration: [
                {
                    "key": "traefik.frontend.rule",
                    "value": "PathPrefixStrip: /api/root"
                }
            ],
            serviceScript: `let TestManager = new MyServiceTypes.TestManager(_SupercondActor);
let results = await TestManager.callAwailableApis(_SupercondActor_Request);
_SupercondActor.Logger.logInfo(['Processed Root API call', results]);
return results;`,
            stopRequested: false
        };
        return serviceConfig;
    }

    getTestApiServiceConfig(runCounter: number): SupercondActor.IApiServiceConfig {
        // provide API service configuration
        let serviceConfig: SupercondActor.IApiServiceConfig = {
            serviceName: `Test API Service #${runCounter}`,
            groupName: 'Generated Services',
            instanceCount: -1,
            metadataJson: '{ "description": "Generated by TestManager scheduled service" }',
            enableADAuthentication: false,
            configureProxy: true,
            serveFiles: false,
            proxyConfiguration: [
                {
                    "key": "traefik.frontend.rule",
                    "value": "PathPrefixStrip: /api/test" + runCounter
                }
            ],
            serviceScript: `let TestManager = new MyServiceTypes.TestManager(_SupercondActor);
let results = await TestManager.getApiServiceInfo();
_SupercondActor.Logger.logInfo(['Test API Service #${runCounter} results', results]);
        return results;`,
            stopRequested: false
        };
        return serviceConfig;
    }

    getTestScheduledServiceConfig(runCounter: number): SupercondActor.IScheduledServiceConfig {
        let serviceConfig: SupercondActor.IScheduledServiceConfig = {
            serviceName: `Test Scheduled Service #${runCounter}`,
            groupName: 'Generated Services',
            metadataJson: '{ "description": "Generated by TestManager scheduled service" }',
                jobSchedule: {
                    intervalSeconds: 15
                },
                stopRequested: false,
                serviceScript: `let TestManager = new MyServiceTypes.TestManager(_SupercondActor);
let results = await TestManager.runSystemTests(${runCounter});
_SupercondActor.Logger.logInfo(['Test Scheduled Service #${runCounter} results', results]);
return results;`        
        };
        return serviceConfig;
    }

    getTestLongRunningServiceConfig(runCounter: number): SupercondActor.ILongRunningServiceConfig {
        let sericeScript = `let TestManager = new MyServiceTypes.TestManager(_SupercondActor);
while (true) {
    let results = await TestManager.runSystemTests(${runCounter});
    _SupercondActor.Logger.logInfo(['Test Long-running Service #${runCounter} results', results]);
    await TestManager.sleep(17000);
}`;
        let serviceConfig: SupercondActor.ILongRunningServiceConfig = {
            serviceName: `Test Long-running Service #${runCounter}`,
            instanceCount: -1,
            groupName: 'Generated Services',
            metadataJson: '{ "description": "Generated by TestManager scheduled service" }',
            stopRequested: true,
            serviceScript: sericeScript
        };
        return serviceConfig;
    }

    async callAwailableApis(rootApiRequest: SupercondActor.IApiRequest) {

        // determine API's base url from the root API request's headers
        let schema = rootApiRequest.headers['X-Forwarded-Proto'][0];
        let host = rootApiRequest.headers['X-Forwarded-Host'][0];
        let port = rootApiRequest.headers['X-Forwarded-Port'][0];
        //let urlPrefix = rootApiRequest.headers['X-Forwarded-Prefix'][0];
        let baseUrl = `${schema}://${host}:${port}`;

        // get list of Apis awailable at the moment
        let apis = await this.supercondActor.Service.getApiServicesAsync(this.appName);
        apis = apis.filter(a => a.serviceInfo.serviceConfig.serviceName.startsWith('Test API Service') && a.serviceInfo.reportedStatus.status === 2);
        let testResults: string[] = [];
        testResults.push(`Found ${apis.length} available Test APIs in application ${this.appName}`);

        // call all APIs async using axios HTTP client
        let apiPrs: AxiosPromise<SupercondActor.IApiServiceInfo>[] = [];
        const axiosInstance = axios.create({
            httpsAgent: new https.Agent({
                rejectUnauthorized: false
            })
        });
        apis.forEach(a => {
            let path = a.serviceInfo.serviceConfig.proxyConfiguration[0].value.substr('PathPrefixStrip: '.length);
            let url = baseUrl + path;
            this.supercondActor.Logger.logInfo(['Calling test API service', a.serviceInfo.serviceConfig.serviceName, url]);
            let resPr = axiosInstance.get<SupercondActor.IApiServiceInfo>(url);
            apiPrs.push(resPr);
        });
        let results = await Promise.all(apiPrs);

        // analyze responses
        results.forEach(r => {
            let requestUrl = r.config.url;
            let serviceClaimedUrlPath = r.data.descriptor.proxyConfiguration[0].value.substr('PathPrefixStrip: '.length);
            if (requestUrl.endsWith(serviceClaimedUrlPath)) {
                testResults.push(`OK for API '${r.data.descriptor.serviceName}' - request URL: ${requestUrl}`);
            }
            else {
                testResults.push(`FAILED for API '${r.data.descriptor.serviceName}' - request URL: ${requestUrl} but path '${serviceClaimedUrlPath}'`);
            }
        });
        return testResults;
    }

    async getApiServiceInfo(): Promise<SupercondActor.IApiServiceInfo> {
        return await this.supercondActor.Service.getServiceDescriptorAsync() as SupercondActor.IApiServiceInfo;
    }

    async requestServiceCounts() {
        let apiPr = this.supercondActor.Service.getApiServicesAsync(this.appName);
        let longrunningPr = this.supercondActor.Service.getLongRunningServicesAsync(this.appName);
        let scheduledPr = this.supercondActor.Service.getScheduledServicesAsync(this.appName);

        const [api, longrunning, scheduled] = await Promise.all([apiPr, longrunningPr, scheduledPr]);

        return {
            apiCount: api.length,
            longrunningCount: longrunning.length,
            scheduledCount: scheduled.length
        };
    }

    async runSystemTests(runCounter: number) {
        let serviceConfig = await this.supercondActor.Service.getServiceDescriptorAsync();

        if (serviceConfig.descriptor.serviceName.endsWith(`#${runCounter}`)) {
            this.supercondActor.Logger.logInfo([`#${runCounter} >> Confirmed service name ${serviceConfig.descriptor.serviceName}`]);
        }
        else {
            throw new Error(`#${runCounter} >> Incorrect service name '${serviceConfig.descriptor.serviceName}'`);
        }
        let counters = await this.requestServiceCounts();
        this.supercondActor.Logger.logInfo([`#${runCounter} >> Service counters`, counters]);
        return counters;
    }

    sleep(ms: number) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}